Add controllers
kasisaki/java-shareit pull request #2
Opened 2023-06-13 20:58 UTC by kasisaki

Часть кода в сыром виде. Делал только по требованиям ТЗ и тестов постмана. Сроки сильно поджимают, поэтому надеюсь, что сможешь проверить оперативно. Спасибо :-)

2023-06-15 13:47 UTC, AnastasiyaFomkina requested changes

2023-06-15 13:47 UTC, AnastasiyaFomkina commented on src/main/java/ru/practicum/shareit/item/ItemController.java
> +    public ItemDto createItem(@RequestHeader(value = "X-Sharer-User-Id") int ownerId,
Лучше вынести повторяющийся хэдер в отдельный класс и сделать его публичной константой, так как он понадобиться еще и в других классах в будущем. Чтобы быстро поправить все значения, можно воспользоваться горячими клавишами в IDEA: [Ctrl+Shift+R](https://www.jetbrains.com/help/idea/finding-and-replacing-text-in-project.html?keymap=primary_windows#replace_search_string_in_project)

2023-06-15 13:47 UTC, AnastasiyaFomkina commented on src/main/java/ru/practicum/shareit/item/ItemController.java
> +                              @Valid @RequestBody Item item) {
В `body` должен приходить `dto-объект`, а не сущность, которую мы собираемся записывать в память программы

2023-06-15 13:47 UTC, AnastasiyaFomkina commented on src/main/java/ru/practicum/shareit/item/ItemController.java
> +                                              @Valid @RequestBody ItemUpdateDto item) {
👍

2023-06-15 13:47 UTC, AnastasiyaFomkina commented on src/main/java/ru/practicum/shareit/item/dto/ItemDto.java
> +    private Boolean available = false;
Инициализация на данном уровне лишняя
```suggestion
    private Boolean available;
```

2023-06-15 13:47 UTC, AnastasiyaFomkina commented on src/main/java/ru/practicum/shareit/item/dto/ItemUpdateDto.java
> +    public Boolean isAvailable() {
Данный метод не используется

2023-06-15 13:47 UTC, AnastasiyaFomkina commented on src/main/java/ru/practicum/shareit/item/mapper/ItemMapper.java
> +    public static ItemDto toItemDto(Item item) {
Нужно будет добавить обратный метод из `ItemDto` в `Item`, чтобы удобно маппить `body`

2023-06-15 13:47 UTC, AnastasiyaFomkina commented on src/main/java/ru/practicum/shareit/item/mapper/ItemMapper.java
> +public class ItemMapper {
_Саморазвитие_
В коммерческой разработке принято максимально избавляться от шаблонного кода, чтобы не перегружать и так большие и объемные проекты. Для маппинга сущностей часто используется библиотека [Mapstruct](https://blog.skillfactory.ru/glossary/mapstruct/), которая позволяет автоматически настраивать маппинг из одной сущности в другую с помощью описания интерфейсов и аннотаций.
Вот [здесь](https://www.baeldung.com/mapstruct) есть отличный гайд для старта работы с библиотекой.
При наличии свободного времени можно поизучать и попробовать прикрутить в проект

2023-06-15 13:47 UTC, AnastasiyaFomkina commented on src/main/java/ru/practicum/shareit/item/ItemService.java
> +    public ItemDto getItem(Integer itemId, Integer ownerId) {
Параметр `ownerId` никак не используется

2023-06-15 13:47 UTC, AnastasiyaFomkina commented on src/main/java/ru/practicum/shareit/item/ItemService.java
> +        for (Item item : items) {
В коммерческой разработке уже почти никто не использует стандартные циклы, так как есть более удобный [stream api](https://stackify.com/streams-guide-java-8/) для работы с коллекциями. Нужно переписать данный цикл с помощью stream api

2023-06-15 13:47 UTC, AnastasiyaFomkina commented on src/main/java/ru/practicum/shareit/item/ItemService.java
> +        for (Item item : items) {
Нужно переписать с помощью stream api

2023-06-15 13:47 UTC, AnastasiyaFomkina commented on src/main/java/ru/practicum/shareit/item/storage/ItemInMemoryStorage.java
> +    private final HashMap<Integer, Item> items = new HashMap<>();
Лучше обозначать интерфейс, а уже инициализировать объект с определенной реализацией. Так программа становится более гибкой и не сломается, если нужно будет подменить реализацию на другую
```suggestion
    private final Map<Integer, Item> items = new HashMap<>();
```

2023-06-15 13:47 UTC, AnastasiyaFomkina commented on src/main/java/ru/practicum/shareit/item/storage/ItemInMemoryStorage.java
> +    private void updateIfNotNull(ItemUpdateDto itemDto, Integer itemId) {
Нужно вынести данный метод в маппер, так как в первую очередь он занимается тем, что маппит `ItemUpdateDto` в `Item`. Выгоднее будет сначала полностью замаппить один объект в другой, чем перезаписывать значения по полям

2023-06-15 13:47 UTC, AnastasiyaFomkina commented on src/main/java/ru/practicum/shareit/item/storage/ItemInMemoryStorage.java
> +    public Item createItem(Item item) {
Нужно использовать возвращаемый тип в сервисе - маппить его в `ItemDto` и отдавать пользователю в контроллере

2023-06-15 13:47 UTC, AnastasiyaFomkina commented on src/main/java/ru/practicum/shareit/item/storage/ItemInMemoryStorage.java
> +    public Integer updateItem(ItemUpdateDto itemDto, Integer itemId, Integer ownerId) {
Здесь нужно возвращать обновленный `Item`, чтобы маппить его в ItemDto и возвращать его пользователю в контроллере

2023-06-15 13:47 UTC, AnastasiyaFomkina commented on src/main/java/ru/practicum/shareit/item/ItemService.java
> +        return ItemMapper.toItemDto(item);
Нужно маппить объект, который мы получили из метода `createItem`, так как мы не можем быть уверены, что после этого метода `Item` останется ровно таким же, какой и пришел

2023-06-15 13:47 UTC, AnastasiyaFomkina commented on src/main/java/ru/practicum/shareit/item/ItemService.java
> +        return ItemMapper.toItemDto(itemStorage.getItem(itemId));
Нужно маппить объект, который получили после метода `updateItem`

2023-06-15 13:47 UTC, afomkina commented on src/main/java/ru/practicum/shareit/user/model/User.java
> +    //@IsNotMatching(matchValue = ".*\\s+.*", message = "Login must not contain spaces")
Нужно удалять код, который не используется, а не комментировать его. В любом случае его всегда можно восстановить из истории коммитов в гите

2023-06-15 13:47 UTC, AnastasiyaFomkina commented on src/main/java/ru/practicum/shareit/user/storage/UserMemoryStorage.java
> +    private final HashMap<Integer, User> usersById = new HashMap<>();
Нужно определять интерфейс, а не конкретную реализацию

2023-06-15 13:47 UTC, AnastasiyaFomkina commented on src/main/java/ru/practicum/shareit/user/storage/UserMemoryStorage.java
> +    private final HashMap<String, User> usersByEmail = new HashMap<>();
Можно сократить до сета

2023-06-15 13:47 UTC, AnastasiyaFomkina commented on src/main/java/ru/practicum/shareit/user/storage/UserMemoryStorage.java
> +    private void updateIfNotNull(User user, Integer id) {
Тоже лучше вынести на уровень маппера

2023-06-15 13:47 UTC, AnastasiyaFomkina commented on src/main/java/ru/practicum/shareit/user/UserController.java
> +    public ResponseEntity<UserDto> createUser(@Valid @RequestBody User user) {
В body должен приходить dto-объект

2023-06-15 13:47 UTC, AnastasiyaFomkina commented on src/main/java/ru/practicum/shareit/user/UserController.java
> +                                              @RequestBody User user) {
В body должен приходить dto-объект

2023-06-15 13:47 UTC, AnastasiyaFomkina commented on src/main/java/ru/practicum/shareit/user/UserService.java
> +        for (User user : usersList) {
Нужно заменить на stream api

2023-06-15 13:47 UTC, AnastasiyaFomkina commented on src/main/java/ru/practicum/shareit/user/UserService.java
> +            //user.setName(user.getLogin());
Нужно удалить закомментированный код

2023-06-16 05:34 UTC, kasisaki commented on src/main/java/ru/practicum/shareit/item/dto/ItemUpdateDto.java
> +    public Boolean isAvailable() {
+

2023-06-16 05:34 UTC, kasisaki commented on src/main/java/ru/practicum/shareit/item/dto/ItemDto.java
> +    private Boolean available = false;
+

2023-06-16 19:29 UTC, kasisaki commented on src/main/java/ru/practicum/shareit/item/ItemController.java
> +                              @Valid @RequestBody Item item) {
+

2023-06-16 19:52 UTC, kasisaki commented on src/main/java/ru/practicum/shareit/item/ItemController.java
> +    public ItemDto createItem(@RequestHeader(value = "X-Sharer-User-Id") int ownerId,
+

2023-06-16 19:52 UTC, kasisaki commented on src/main/java/ru/practicum/shareit/user/storage/UserMemoryStorage.java
> +    private void updateIfNotNull(User user, Integer id) {
+

2023-06-16 20:53 UTC, kasisaki commented on src/main/java/ru/practicum/shareit/item/mapper/ItemMapper.java
> +public class ItemMapper {
Спасибо. Возьму на заметку и при первой возможности попробую внедрить. Пока со временем очень туго. Дедлайн на носу.

2023-06-16 21:01 UTC, kasisaki commented on src/main/java/ru/practicum/shareit/item/ItemService.java
> +        for (Item item : items) {
+

2023-06-16 21:07 UTC, kasisaki commented on src/main/java/ru/practicum/shareit/item/storage/ItemInMemoryStorage.java
> +    private final HashMap<Integer, Item> items = new HashMap<>();
+

2023-06-16 22:07 UTC, kasisaki commented on src/main/java/ru/practicum/shareit/item/ItemService.java
> +        return ItemMapper.toItemDto(item);
+

2023-06-16 22:09 UTC, kasisaki commented on src/main/java/ru/practicum/shareit/item/ItemService.java
> +        return ItemMapper.toItemDto(itemStorage.getItem(itemId));
+

2023-06-16 22:09 UTC, kasisaki commented on src/main/java/ru/practicum/shareit/user/model/User.java
> +    //@IsNotMatching(matchValue = ".*\\s+.*", message = "Login must not contain spaces")
+

2023-06-16 22:10 UTC, kasisaki commented on src/main/java/ru/practicum/shareit/user/storage/UserMemoryStorage.java
> +    private final HashMap<Integer, User> usersById = new HashMap<>();
+

2023-06-16 22:14 UTC, kasisaki commented on src/main/java/ru/practicum/shareit/user/storage/UserMemoryStorage.java
> +    private final HashMap<String, User> usersByEmail = new HashMap<>();
При сокращении до сета возникнут проблемы при попытке обновить почту юзера на другую, которая уже занята
 по условию почта должна быть уникальной

2023-06-16 22:14 UTC, kasisaki commented on src/main/java/ru/practicum/shareit/user/UserController.java
> +    public ResponseEntity<UserDto> createUser(@Valid @RequestBody User user) {
+

2023-06-16 22:15 UTC, kasisaki commented on src/main/java/ru/practicum/shareit/user/UserController.java
> +                                              @RequestBody User user) {
+

2023-06-16 22:26 UTC, kasisaki commented on src/main/java/ru/practicum/shareit/user/UserService.java
> +        for (User user : usersList) {
+

2023-06-16 22:27 UTC, kasisaki commented on src/main/java/ru/practicum/shareit/user/UserService.java
> +            //user.setName(user.getLogin());
+

2023-06-16 22:28 UTC, kasisaki commented on src/main/java/ru/practicum/shareit/item/storage/ItemInMemoryStorage.java
> +    public Integer updateItem(ItemUpdateDto itemDto, Integer itemId, Integer ownerId) {
+

2023-06-17 17:10 UTC, AnastasiyaFomkina approved these changes

2023-06-17 17:10 UTC, AnastasiyaFomkina commented on src/main/java/ru/practicum/shareit/user/storage/UserMemoryStorage.java
> +    //При сокращении до сета возникнут проблемы при попытке обновить почту юзера на другую, которая уже занята
В сете не может храниться дублей - соответственно, проблем с обновлением тоже быть не должно. 
Когда нужно обновить почту пользователя, и если такой почты нет в сете - она не занята и можно ее обновлять.
Если она там есть - значит, уже есть другой пользователь с такой почтой, и обновить ее нельзя. 
Если при обновлении почта соответствует той, что была уже записана у пользователя, то ее обновлять не нужно.

2023-06-17 22:20 UTC, merged