Add bookings
kasisaki/java-shareit pull request #3
Opened 2023-06-20 23:35 UTC by kasisaki

2023-06-25 07:01 UTC, krylov-sergey-sergeevich requested changes
Привет, неплохо, но давай местами доработаем =)

2023-06-25 07:01 UTC, krylov-sergey-sergeevich commented on pom.xml
> +			<version>42.3.2</version>
версию можно в проперти блок вынести

2023-06-25 07:01 UTC, krylov-sergey-sergeevich commented on pom.xml
> +		<dependency>
Для чего это? У нас в теории все от спринга должно хватить

2023-06-25 07:01 UTC, krylov-sergey-sergeevich commented on src/main/java/ru/practicum/shareit/booking/BookingService.java
> +        LocalDateTime now = LocalDateTime.now();
Давай создадим класс DateUtils и будем создавать объекты времени через него, это позволит унифицировать способ получения времени и если будут правки делать их в 1 месте.

DateUtils.now()

2023-06-25 07:01 UTC, krylov-sergey-sergeevich commented on src/main/java/ru/practicum/shareit/booking/BookingService.java
> +        if (!userRepository.existsById(ownerId)) {
Эти три строки дублируются в 2 местах можно подумать о методе

2023-06-25 07:01 UTC, krylov-sergey-sergeevich commented on src/main/java/ru/practicum/shareit/booking/model/Booking.java
> +    @Enumerated(EnumType.ORDINAL)
@Enumerated(EnumType.STRING) - так получше

2023-06-25 07:01 UTC, krylov-sergey-sergeevich commented on src/main/java/ru/practicum/shareit/exception/ErrorHandler.java
> +public class ErrorHandler extends ResponseEntityExceptionHandler {
А для чего наследуемся?

2023-06-25 07:01 UTC, krylov-sergey-sergeevich commented on src/main/java/ru/practicum/shareit/item/ItemService.java
> +        LocalDateTime now = LocalDateTime.now();
Заменить на DateUtils можно будет

2023-06-25 07:01 UTC, krylov-sergey-sergeevich commented on src/main/java/ru/practicum/shareit/item/dto/ItemDto.java
> +    BookingDtoShort lastBooking;
модификаторы доступа

2023-06-25 07:01 UTC, krylov-sergey-sergeevich commented on src/main/resources/schema.sql
> +DROP ALL OBJECTS DELETE FILES;
Опасная операция, на продакшене не пользуемся но в рамках учебного проекта ок

2023-06-25 07:01 UTC, krylov-sergey-sergeevich commented on src/main/resources/schema.sql
> +    CONSTRAINT UQ_USER_EMAIL UNIQUE (email)
Рекомендую ключ создавать вот так CONSTRAINT pk_user PRIMARY KEY (user_id),

2023-06-25 07:01 UTC, krylov-sergey-sergeevich commented on src/main/resources/schema.sql
> +    time_created  TIMESTAMP     not null
TIMESTAMP WITHOUT TIME ZONE NOT NULL,

2023-06-25 09:01 UTC, kasisaki commented on pom.xml
> +		<dependency>
Starting with Boot 2.3, we also need to explicitly add the spring-boot-starter-validation dependency:

2023-06-25 09:24 UTC, kasisaki commented on src/main/java/ru/practicum/shareit/booking/BookingService.java
> +        if (!userRepository.existsById(ownerId)) {
заменил на вызов метода в 3 местах

2023-06-25 09:24 UTC, kasisaki commented on src/main/java/ru/practicum/shareit/booking/BookingService.java
> +        LocalDateTime now = LocalDateTime.now();
+

2023-06-25 09:24 UTC, kasisaki commented on pom.xml
> +			<version>42.3.2</version>
+

2023-06-25 09:30 UTC, kasisaki commented on src/main/resources/schema.sql
> +DROP ALL OBJECTS DELETE FILES;
согласен. Для моих целей достаточно было бы spring.jpa.hibernate.ddl-auto=create-drop прописать в пропертиз.

2023-06-25 09:31 UTC, kasisaki commented on src/main/resources/schema.sql
> +    time_created  TIMESTAMP     not null
+

2023-06-26 12:52 UTC, krylov-sergey-sergeevich approved these changes
Привет, вижу правки - зачет!

2023-06-26 20:21 UTC, merged