Add item requests
kasisaki/java-shareit pull request #4
Opened 2023-06-28 21:44 UTC by kasisaki

2023-06-29 05:12 UTC, krylov-sergey-sergeevich requested changes
Привет, очень неплохо - давай обсудим и поправим что отметил и будем завершать работу =)

2023-06-29 05:12 UTC, krylov-sergey-sergeevich commented on src/main/java/ru/practicum/shareit/booking/BookingController.java
>  public class BookingController {
@Slf4j - можно логи докинуть

2023-06-29 05:12 UTC, krylov-sergey-sergeevich commented on src/main/java/ru/practicum/shareit/item/ItemController.java
@Slf4j - можно логи докинуть

2023-06-29 05:12 UTC, krylov-sergey-sergeevich commented on src/main/java/ru/practicum/shareit/item/ItemController.java
@PositiveOrZero @RequestParam(name = "from", defaultValue = "0") Integer from,
			@Positive @RequestParam(name = "size", defaultValue = "10") Integer size

вроде  в пару методов в контроллерах можно/нужно еще пагинацию докинуть

2023-06-29 05:12 UTC, krylov-sergey-sergeevich commented on src/main/java/ru/practicum/shareit/booking/BookingService.java
@Transactional(readOnly = true)
давай накинем на класс и где нужно уже повесим Transactional на метод

2023-06-29 05:12 UTC, krylov-sergey-sergeevich commented on src/main/java/ru/practicum/shareit/item/ItemService.java
Давай проверим метод getItemsOfOwner есть ощущение что в рамках него слишком много запросов в БД идет, нельзя получше сделать?

2023-06-29 05:12 UTC, krylov-sergey-sergeevich commented on src/main/java/ru/practicum/shareit/request/ItemRequestService.java
> +        return requestToItemRequestDto(itemRequestRepository.save(dtoToItemRequest(requestDto, userRepository.findById(requestorId).orElseThrow(
читается очень больно, давай на строки распишем и переменные выделим внутри

2023-06-29 06:52 UTC, kasisaki commented on src/main/java/ru/practicum/shareit/booking/BookingController.java
>  public class BookingController {
+

2023-06-29 07:13 UTC, kasisaki commented on src/main/java/ru/practicum/shareit/item/ItemController.java
+

2023-06-30 03:48 UTC, krylov-sergey-sergeevich approved these changes
Привет вижу правки - зачет!

2023-06-30 03:48 UTC, krylov-sergey-sergeevich commented on src/main/java/ru/practicum/shareit/item/ItemService.java
> +        return itemRepository.findAllByOwnerIdOrderByIdAsc(ownerId, pageable).stream().map(this::retrieveWithBookingInfo)
Надо точно улучшать, если есть запрос где идет кол-во запросов зависимое от кол-во сущностей это оч плохо так как может рано или поздно стать сотни или тысячи запросов

2023-06-30 03:48 UTC, krylov-sergey-sergeevich commented on src/main/java/ru/practicum/shareit/item/ItemService.java
> +        return itemRepository.findAllByOwnerIdOrderByIdAsc(ownerId, pageable).stream().map(this::retrieveWithBookingInfo)
Давай к следующему дз проработаешь

2023-06-30 16:09 UTC, merged